# Generated by Django 5.2 on 2026-01-09 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anonimo', models.BooleanField(default=True)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('phone', 'Teléfono'), ('presencial', 'Presencial')], default='web', max_length=20)),
                ('relacion_empresa', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('nombre_denunciado', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=255)),
                ('tipo_incidente', models.CharField(choices=[('fraud', 'Fraude'), ('harassment', 'Acoso'), ('discrimination', 'Discriminación'), ('corruption', 'Corrupción'), ('safety', 'Seguridad'), ('other', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_aproximada', models.CharField(blank=True, max_length=100)),
                ('es_continuo', models.BooleanField(default=False)),
                ('ciudad', models.CharField(blank=True, max_length=255)),
                ('relacionado_trabajo', models.BooleanField(default=True)),
                ('tiene_evidencia', models.BooleanField(default=False)),
                ('descripcion_evidencia', models.TextField(blank=True)),
                ('datos_json', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
